/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaoluIndexRouteImport } from './routes/taolu/index'
import { Route as TaoluNameRouteImport } from './routes/taolu/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaoluIndexRoute = TaoluIndexRouteImport.update({
  id: '/taolu/',
  path: '/taolu/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaoluNameRoute = TaoluNameRouteImport.update({
  id: '/taolu/$name',
  path: '/taolu/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/taolu/$name': typeof TaoluNameRoute
  '/taolu/': typeof TaoluIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/taolu/$name': typeof TaoluNameRoute
  '/taolu': typeof TaoluIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/taolu/$name': typeof TaoluNameRoute
  '/taolu/': typeof TaoluIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/taolu/$name' | '/taolu/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/taolu/$name' | '/taolu'
  id: '__root__' | '/' | '/taolu/$name' | '/taolu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaoluNameRoute: typeof TaoluNameRoute
  TaoluIndexRoute: typeof TaoluIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taolu/': {
      id: '/taolu/'
      path: '/taolu'
      fullPath: '/taolu/'
      preLoaderRoute: typeof TaoluIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taolu/$name': {
      id: '/taolu/$name'
      path: '/taolu/$name'
      fullPath: '/taolu/$name'
      preLoaderRoute: typeof TaoluNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaoluNameRoute: TaoluNameRoute,
  TaoluIndexRoute: TaoluIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
